apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../default
patches:
  - target:
      kind: Deployment
      name: agent-control-api
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: agent-control-api
      spec:
        template:
          spec:
            containers:
              - name: api
                env:
                  - name: EXECUTION_MODE
                    value: live
