apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bases/agents.governed.io_agents.yaml
  - bases/agents.governed.io_agentruns.yaml
  - bases/agents.governed.io_tenantpolicies.yaml

